TARGET := libPropertyManager.a

OBJS := \
	PropertyManager.o \
	CstiPropertySender.o \
	PropertyListItem.o


DEFS := 

INSTALL_FILES := \
	PropertyManager.h \
	PropertyListItem.h

INCS := \
	-I$(PM_INCLUDE_DIR) \
	-I$(IXML_DIR)/inc \
	-I$(COMMON_DIR) \
	-I$(OS_DIR) \
	-I$(SERVICES_DIR) \
	-I$(CORE_SERVICE_DIR) \
	-I$(HTTP_DIR) \
	-I$(XMLMGR_INCLUDE_DIR)

include $(MAKEFILE_RULES)

