TARGET := libstiConferenceService.a

DEFS := 

INCS := \
	-I$(SERVICES_DIR) \
	-I$(CORE_SERVICE_DIR) \
	-I$(COMMON_DIR) \
	-I$(OS_DIR) \
	-I$(IXML_DIR)/inc \
	-I$(HTTP_DIR) \
	-I$(PM_INCLUDE_DIR) \
	-I$(XMLMGR_INCLUDE_DIR) \
	-I$(CONFMGR_DIR)
	
INSTALL_FILES := \
	CstiConferenceRequest.h \
	CstiConferenceResponse.h

DOC_FILES := \
	CstiConferenceRequest.h \
	CstiConferenceResponse.h
	
OBJS := \
	CstiConferenceRequest.o \
	CstiConferenceResponse.o \
	CstiConferenceService.o

include $(MAKEFILE_RULES)

