TARGET := libFilePlay.a

OBJS := \
	CFilePlay.o \

DEFS := 
	
CHILD_DIRECTORIES := \
	MPEG4 

INCS := \
	-I$(COMMON_DIR) \
	-I$(OS_DIR) \
	-I$(PLATFORM_DIR) \
	-IMPEG4/Toolbox \
	-IMPEG4 \
	-I$(CONFMGR_DIR) \
	-I$(CONFMGR_DIR)/Session \
	-I$(PLATFORM_DIR)/common/wireless \
	-I$(HTTP_DIR) 

include $(MAKEFILE_RULES)

