TARGET := libAudioBridge.a

OBJS := CstiAudioBridge.o \
	BaseAudioInput.o \
	BaseAudioOutput.o

DEFS := 

INCS := \
	-I$(PLATFORM_DIR)/Audio \
	-I$(PLATFORM_DIR) \
	-I$(OS_DIR) \
	-I$(COMMON_DIR)

INSTALL_FILES := \
	BaseAudioInput.h \
	BaseAudioOutput.h

include $(MAKEFILE_RULES)

