//////////////////////////////////////////////////////////////////////////////
//
// Sorenson Communications Inc. Confidential. --  Do not distribute
// Copyright 2015 Sorenson Communications, Inc. -- All rights reserved
//
//	File Name:	SorensonErrors.h
//
//  Abstract:	File contains #defines of all error codes.
//
//////////////////////////////////////////////////////////////////////////////
#ifndef SORENSONERRORS_H
#define SORENSONERRORS_H

#define SMRES_SUCCESS							0
#define SMRES_ALLOC_FAILED						1
#define SMRES_FIFO_OVERFLOW						2
#define SMRES_FIFO_UNGET_ERROR					3
#define SMRES_EOS								4
#define SMRES_INVALID_HEADER					5
#define SMRES_UNSUPPORTED_PICTYPE				6
#define SMRES_INVALID_PICSIZE					7
#define SMRES_INVALID_PREDICTION_MODE			8
#define SMRES_INVALID_REFERENCE_NUMBER			9
#define SMRES_INVALID_SIZE_CHANGE				10
#define SMRES_UNSUPPORTED_FEATURE				11
#define SMRES_INVALID_BITSTREAM					12
#define SMRES_HUFF_ENC_INDEX_ERROR				13
#define SMRES_PACKET_TOO_SMALL					14
#define SMRES_INVALID_DELTAQUANT				15
#define SMRES_INVALID_STRUCTURE					16
#define SMRES_UNREGISTERED_MEDIA_KEY			17
#define SMRES_INVALID_SERIAL_NUMBER				18
#define SMRES_IMAGEDESC_ERROR					19
#define SMRES_DEFAULT_COMPONENT_ERROR			20
#define SMRES_FIFO_RESIZE_FAILED				21
#define SMRES_FIFO_TOO_SMALL					22
#define SMRES_INVALID_SETTINGS_SIZE				23
#define SMRES_INVALID_PACKET_SIZE				24
#define SMRES_INVALID_BLOCK_REFRESH_RATE		25
#define SMRES_INVALID_SCENE_CHANGE_SENSITIVITY	26
#define SMRES_INVALID_MINIMUM_QUALITY			27
#define SMRES_INVALID_COMPRESSION_SPEED			28
#define SMRES_INVALID_MEDIA_KEY					29
#define SMRES_SIZE_CHANGE						30
#define SMRES_INVALID_DROP_FRAMES				31
#define SMRES_INVALID_BFRM_MODE					32
#define SMRES_INVALID_MP_NUM					33
#define SMRES_INVALID_SHAPE						34
#define SMRES_INVALID_SHAPE_EXT					35
#define SMRES_INVALID_ALPHA_LOSSY_TH			36
#define SMRES_INVALID_FEATHER_EFFECT			37
#define SMRES_INVALID_FEATHER_DISTANCE			38
#define SMRES_INVALID_MAX_OPACITY				39
#define SMRES_INVALID_RGB						40
#define SMRES_INVALID_COLOR_VECTOR_SPREAD		41
#define SMRES_INVALID_SWATCH					42
#define SMRES_INVALID_WATERMARK					43
#define SMRES_INVALID_BLOCK_MODE				44
#define SMRES_INVALID_BITRATE					45
#define SMRES_INVALID_BLOCK_NUMBER				46
#define SMRES_INVALID_DQUANT					47
#define SMRES_INVALID_MVD_RANGE					48
#define SMRES_INVALID_INSTANCE					49
#define SMRES_INVALID_COLOR_FORMAT				50
#define SMRES_INVALID_PARAMETER					51
#define SMRES_INVALID_MOVIE						52
#define SMRES_INVALID_DATA_HANDLER				53
#define SMRES_INVALID_FILENAME					54
#define SMRES_INVALID_TRACK						55
#define SMRES_INVALID_MEDIA						56
#define SMRES_INVALID_MEDIA_TYPE				57
#define SMRES_INVALID_REFRENCE					58
#define SMRES_INVALID_OBJECT_ID					59
#define SMRES_INVALID_URL						60
#define SMRES_INVALID_PROFILE					61
#define SMRES_NO_SIZE_INFORMATION				62
#define SMRES_INVALID_MV_RANGE					63
#define SMRES_INVALID_QUANT_TYPE				64
#define SMRES_INVALID_QUANT_MATRIX				65
#define SMRES_NO_COLOR_KEY_SUPPORT				66
#define SMRES_INVALID_WARPING_MODEL				67
#define SMRES_INVALID_WARPING_PRECISION			68
#define SMRES_INVALID_WARPING_PARAMETERS		69
#define SMRES_INVALID_SPRITE_MVD				70
#define SMRES_INVALID_SETTINGS_STRUCTURE		71
#define SMRES_READ_ERROR						72
#define SMRES_WRITE_ERROR						73
#define SMRES_INVALID_GMC_USAGE					74
#define SMRES_INVALID_MCPRED_IMAGE				75
#define SMRES_INVALID_SAMPLE_DESCRIPTION		76
#define SMRES_INVALID_INDEX						77
#define SMRES_INVALID_ES_DESCRIPTOR				78
#define SMRES_INVALID_OBJECT					79
#define SMRES_INVALID_OBJECT_COMMAND			80
#define SMRES_INVALID_DECODER_SPECIFIC			81
#define SMRES_UNSUPPORTED_DECODER_CONFIG		82
#define SMRES_UNSUPPORTED_OBJECT_COMMAND		83
#define SMRES_UNSUPPORTED_SL_CONFIG				84
#define SMRES_INVALID_INIT_OBJ_DESCRIPTOR		85
#define SMRES_INVALID_OBJ_DESCRIPTOR			86
#define SMRES_INVALID_DESCRIPTOR				87
#define SMRES_INVALID_PACKET_BUILDER			88
#define SMRES_INVALID_PACKET_GROUP_REF			89
#define SMRES_INVALID_PACKET_REF				90
#define SMRES_BASE64_ENCODE_ERROR				91
#define SMRES_INVALID_SDP_MEDIA_TYPE			92
#define SMRES_UNSUPPORTED_PACKET_ENTRY			93
#define SMRES_UNSUPPORTED_SAMPLE_DESCRIPTION	94
#define SMRES_INVALID_AUDIO_HEADER				95
#define SMRES_UNSUPPORTED_AUDIO_HEADER_FEATURE	96
#define SMRES_UNSUPPORTED_SIZE					97
#define SMRES_FILE_OPEN_FAILED					98
#define SMRES_INVALID_CODEC						99
#define SMRES_OFFSET_OVERWRITTEN				100
#define SMRES_OFFSET_NO_YET_AVAIL				101
#define SMRES_OFFSET_PAST_EOF					102

#endif // SORENSONERRORS_H


