TARGET := libstiRemoteLoggerService.a

DEFS := 

INCS := \
	-I$(SERVICES_DIR) \
	-I$(CORE_SERVICE_DIR) \
	-I$(LOGGER_SERVICE_DIR) \
	-I$(COMMON_DIR) \
	-I$(OS_DIR) \
	-I$(IXML_DIR)/inc \
	-I$(HTTP_DIR) \
	-I$(PM_INCLUDE_DIR) \
	-I$(XMLMGR_INCLUDE_DIR) \
	-I$(CONFMGR_DIR)
	
INSTALL_FILES := \
	CstiRemoteLoggerRequest.h

DOC_FILES := 
	
OBJS := \
	CstiRemoteLoggerRequest.o \
	CstiRemoteLoggerService.o

include $(MAKEFILE_RULES)

