TARGET := libAtoms.a

OBJS := \
	Atom.o \
	FullAtom.o \
	UdtaAtom.o \
	TrakAtom.o \
	TkhdAtom.o \
	MvhdAtom.o \
	MoovAtom.o \
	FtypAtom.o \
	MdiaAtom.o \
	MinfAtom.o \
	StblAtom.o \
	MdhdAtom.o \
	HdlrAtom.o \
	VmhdAtom.o \
	SmhdAtom.o \
	HmhdAtom.o \
	NmhdAtom.o \
	DrefAtom.o \
	SttsAtom.o \
	CttsAtom.o \
	StsdAtom.o \
	StszAtom.o \
	StscAtom.o \
	StcoAtom.o \
	StssAtom.o \
	ElstAtom.o \
	TrefAtom.o \
	UrlAtom.o \
	UrnAtom.o \
	DinfAtom.o \
	UnknownAtom.o \
	

DEFS := 

INCS := \
	-I$(PLATFORM_COMMON_DIR)/fileplay/MPEG4/Atoms \
	-I$(PLATFORM_COMMON_DIR)/fileplay/MPEG4 \
	-I$(PLATFORM_COMMON_DIR)/fileplay/MPEG4/Toolbox \
	-I$(OS_DIR) \
	-I$(COMMON_DIR)

include $(MAKEFILE_RULES)

