
TARGET := libCommonVideo.a

OBJS =  \
	VideoPlaybackFrame.o \
	BaseVideoInput.o \
	BaseVideoOutput.o

CHILD_DIRECTORIES = 

INCS += \
	-I$(PLATFORM_DIR) \
	-I$(COMMON_DIR) \
	-I$(OS_DIR)

INSTALL_FILES := \
	BaseVideoInput.h \
	BaseVideoOutput.h

include $(MAKEFILE_RULES)
