TARGET := libCommonNetwork.a

OBJS := \
	BaseNetwork.o

DEFS := 

INCS := \
	-I$(PLATFORM_DIR) \
	-I$(PLATFORM_COMMON_DIR)/wireless \
	-I$(COMMON_DIR) \
	-I$(OS_DIR)

INSTALL_FILES := \
	BaseNetwork.h

include $(MAKEFILE_RULES)

