TARGET := libFileDownload.a

OBJS := \
	CstiFileDownloadHandler.o \

DEFS := 
	
INSTALL_FILES := \
	IstiFileDownloadHandler.h 

DOC_FILES := \
	IstiFileDownloadHandler.h

INCS := \
	-I$(COMMON_DIR) \
	-I$(OS_DIR) \
	-I$(PLATFORM_DIR) \
	-I$(HTTP_DIR)

include $(MAKEFILE_RULES)

