TARGET := libstiTextRecord.a

OBJS := \
	CstiTextRecord.o

DEFS := \
	-DstiSILENCE_SUPPRESSION

INCS := \
	-I$(OBSERVER_PTR_DIR) \
	-I$(COMMON_DIR) \
	-I$(OS_DIR) \
	-I$(PLATFORM_DIR) \
	-I$(IXML_DIR)/inc \
	-I$(PM_INCLUDE_DIR) \
	-I$(XMLMGR_INCLUDE_DIR) \
	-I$(RVSHAREDDIR_INC) \
	-I$(RVSHAREDDIR_INC)/common \
	-I$(RVSHAREDDIR_INC)/asn1 \
	-I$(RVSHAREDDIR_INC)/artp \
	-I$(RVSHAREDDIR_INC)/ads \
	-I$(RVSHAREDDIR_INC)/sip \
	-I$(RVSHAREDDIR_INC)/sdp \
	-I$(ACMEDIR_INC) \
	-I$(CONFMGR_DIR) \
	-I$(CONFMGR_DIR)/DataTasks/DataCommon \
	-I$(CONFMGR_DIR)/Session

include $(MAKEFILE_RULES)

