TARGET := libCstiRegistrationManager.a

OBJS := \
	CstiRegistrationManager.o \
	CstiRegistrationList.o \
	CstiRegistrationListItem.o

DEFS :=

INCS := \
	-I$(REGISTRATIONMGR_DIR) \
	-I$(COMMON_DIR) \
	-I$(XMLMGR_INCLUDE_DIR) \
	-I$(IXML_DIR)/inc \
	-I$(SERVICES_DIR) \
	-I$(CORE_SERVICE_DIR) \
	-I$(CONFMGR_DIR) \
	-I$(OS_DIR)

INSTALL_FILES :=

DOC_FILES :=

include $(MAKEFILE_RULES)

