TARGET := libstiAudioPlayback.a

OBJS := \
	CstiAudioPlayback.o \
	CstiAudioPlaybackRead.o

DEFS := \
	-DstiSILENCE_SUPPRESSION

INCS := \
	-I$(OBSERVER_PTR_DIR) \
	-I$(COMMON_DIR) \
	-I$(OS_DIR) \
	-I$(PLATFORM_DIR) \
	-I$(RVSHAREDDIR_INC) \
	-I$(RVSHAREDDIR_INC)/common \
	-I$(RVSHAREDDIR_INC)/ads \
	-I$(RVSHAREDDIR_INC)/sip \
	-I$(RVSHAREDDIR_INC)/sdp \
	-I$(RVSHAREDDIR_INC)/artp \
	-I$(RVSHAREDDIR_INC)/turn \
	-I$(RVSHAREDDIR_INC)/stun \
	-I$(ACMEDIR_INC) \
	-I$(CONFMGR_DIR) \
	-I$(CONFMGR_DIR)/DataTasks/DataCommon \
	-I$(CONFMGR_DIR)/Session \
	-I$(IXML_DIR)/inc \
	-I$(PM_INCLUDE_DIR) \
	-I$(XMLMGR_INCLUDE_DIR)

include $(MAKEFILE_RULES)


