TARGET := libUserAccountMgr.a

OBJS := \
	UserAccountListItem.o \
	UserAccountManager.o 

DEFS :=

INCS := \
	-I$(XMLMGR_INCLUDE_DIR) \
	-I$(IXML_DIR)/inc \
	-I$(COMMON_DIR) \
	-I$(OS_DIR) \
	-I$(SERVICES_DIR) \
	-I$(CORE_SERVICE_DIR) \
	-I$(STATENOTIFY_SERVICE_DIR) \
	-I$(HTTP_DIR) \

INSTALL_FILES := \
	IUserAccountManager.h

DOC_FILES :=

include $(MAKEFILE_RULES)

