TARGET := libSerialization.a

OBJS := \
	JsonFileSerializer.o

DEFS :=

INCS := \
	-I$(OS_DIR) \
	-I$(COMMON_DIR)

INSTALL_FILES := \
	ISerializable.h \
	SerializedProperty.h \
	JsonSerializer.h
	

DOC_FILES :=

include $(MAKEFILE_RULES)

