TARGET := libFileUpload.a

OBJS := \
	CstiFileUploadHandler.o \

DEFS := 
	
INSTALL_FILES := \
	IstiFileUploadHandler.h 

DOC_FILES := \
	IstiFileUploadHandler.h

INCS := \
	-I../common \
	-I../os \
	-I../Platform \
	-I../http

include $(MAKEFILE_RULES)

