TARGET := libstiUpdate.a

CHILD_DIRECTORIES = 

OBJS := CstiUpdateWriter.o \
	CstiUpdateConnection.o \
	CstiUpdate.o

DEFS := 

INCS := \
	-I$(COMMON_DIR) \
	-I$(OS_DIR) \
	-I$(HTTP_DIR) \
	-I$(PLATFORM_DIR) \
	-I$(VP_COMMON_DIR)

include $(MAKEFILE_RULES)

