TARGET := libstiNat.a

CHILD_DIRECTORIES := 

OBJS := \
	CstiIceManager.o \
	CstiIceSession.o

DEFS :=

INSTALL_FILES :=

DOC_FILES :=

INCS := \
	-I$(CONFMGR_DIR)/Nat \
	-I$(CONFMGR_DIR)/Session \
	-I$(CONFMGR_DIR)/DataTasks/DataCommon \
	-I$(CONFMGR_DIR) \
	-I$(COMMON_DIR) \
	-I$(OS_DIR) \
	-I$(RVSHAREDDIR_INC) \
	-I$(RVSHAREDDIR_INC)/common \
	-I$(RVSHAREDDIR_INC)/artp \
	-I$(RVSHAREDDIR_INC)/sip \
	-I$(RVSHAREDDIR_INC)/ice \
	-I$(RVSHAREDDIR_INC)/turn \
	-I$(RVSHAREDDIR_INC)/stun \
	-I$(RVSHAREDDIR_INC)/sdp \
	-I$(RVSHAREDDIR_INC)/ads \
	-I$(ACMEDIR_INC)

include $(MAKEFILE_RULES)

