TARGET := libUICommon.a

INCS := \
 	-I$(VIDEOPHONE_ENGINE_PATH) \
	-I$(PEGINCLUDE) \
	-I$(PEGINCLUDE)/keybddrv \
	-I$(PEGINCLUDE)/rtos \
	-I$(PEGINCLUDE)/screendrv

OBJS := \
	propertydef.o \
	validator.o \
	SecretCodeParser.o \
    ErrorCodeLookup.o

DEFS:= 

include $(MAKEFILE_RULES)

